x=imread('C:\Users\STUDENT\Desktop\oip.jpg')
subplot(3,3,1)
imshow('C:\Users\STUDENT\Desktop\oip.jpg')
title('Original image')
y=im2bw(x,0.5)
subplot(3,3,2)
imshow(y)
title('Black and white image')
z=rgb2gray(x)
subplot(3,3,3)
imshow(z)
title('Gray image')
v=imcrop(x,[50 50 50 50])
subplot(3,3,4)
imshow(v)
title('Cropped image')
b=imresize(x,0.5)
subplot(3,3,5)
imshow(b)
title('Resized image’)